apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe-route-frontend
  namespace: safe-route
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safe-route-frontend
  template:
    metadata:
      labels:
        app: safe-route-frontend
    spec:
      containers:
        - name: frontend
          # Replace this image with your frontend image
          image: vijayreddygoli811/saferoute-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-svc:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: safe-route
spec:
  selector:
    app: safe-route-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  type: NodePort
